languaje: java
sudo: false
jdk:
- oraclejdk7
env:
  global:
  - secure: Tp3CUKlwhrUvcAI/LqlWhnk3pU57iwnzfVhukxB0thXXLLkfrGVGKWeOFQo9DPFbu+k2YC1A3tcnDMK771iYGmAz8Cyh+jK5dl/dHdUqFyjd0C2eos9IZlXjo0IVMBQInoHxpZXnRLeWN6sct6LntFgM6cOCx7lTDcVUY84LUKY=
before_script:
- rm -rf $TRAVIS_BUILD_DIR/gen-badge 2> /dev/null
- rm -rf $TRAVIS_BUILD_DIR/pro-gen.github.io 2> /dev/null
- git clone https://github.com/jirsis/gen-badge.git $TRAVIS_BUILD_DIR/gen-badge
- git clone https://${GH_TOKEN}@github.com/pro-gen/pro-gen.github.io.git $TRAVIS_BUILD_DIR/pro-gen.github.io
script:
- cd progen
- mvn clean verify site jacoco:report coveralls:jacoco
after_success:
- mkdir $TRAVIS_BUILD_DIR/progen/target/pmd
- cp $TRAVIS_BUILD_DIR/progen/target/pmd.xml $TRAVIS_BUILD_DIR/progen/target/pmd
- mvn xml:transform
- cp $TRAVIS_BUILD_DIR/progen/target/generated-resources/xml/xslt/pmd.xml $TRAVIS_BUILD_DIR/progen/target/site/pmd.html
- node -v
- cd $TRAVIS_BUILD_DIR/gen-badge
- npm install
- "./gen-badges.js $TRAVIS_BUILD_DIR/progen/target/"
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis-CI deployer"
- cd $TRAVIS_BUILD_DIR/pro-gen.github.io
- cp -v $TRAVIS_BUILD_DIR/progen/target/*svg .
- cp -v $TRAVIS_BUILD_DIR/progen/target/*xml .
- mkdir reports 2> /dev/null
- cp -r $TRAVIS_BUILD_DIR/progen/target/site/* reports
- git add -f *svg pmd.xml findbugs.xml checkstyle-result.xml
- git add -f reports/*
- git commit -q -m "Travis build $TRAVIS_BUILD_NUMBER pushed to ProGen page"
- git push -fq origin master
